name: Build Test and Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_and_execute_unit_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"
      - name: Install Dependencies
        run: npm install
      - name: Execute unit tests
        run: npm run test:unit
      - name: Display my Sofuni username
        run: echo 'Embarata'

  execute_UI_tests:
    needs: build_and_execute_unit_tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"
      - name: Install Dependencies
        run: npm install
      - name: Install browsers for playwright
        run: npx playwright install
      - name: Start application
        run: npm run start &
      - name: Execute UI tests
        run: npm run test:ui

  deploy_to_render:
    needs: execute_UI_tests
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          wait_deploy: true
