name: Build Test and Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_and_execute_unit_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"
      - name: Install Dependencies
        run: npm install
      - name: Execute unit tests
        run: npm run test:unit
      - name: Display my Sofuni username
        run: echo 'Embarata'
  Execute_UI_tests:
    needs: build_and_execute_unit_tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"
      - name: Install Dependencies
        run: npm install
      - name: Install browsers for playwright
        run: npx playwright install
      - name: Execute UI tests
        run: npm run test:ui
